apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW4= #longhorn-test-access-key #echo -n "admin" | base64 
  AWS_SECRET_ACCESS_KEY: MTIzRW1waXJpeCE= #longhorn-test-secret-key #echo -n "YWRtaW4=" | base64 --decode
  AWS_ENDPOINTS: aHR0cHM6Ly8xMC45My4xNy4zk6OTAwMC9taW5pby8=  #https://minio-service.default:9000
