apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    name: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-pwd
type: Opaque
data:
  password: cGVyZmVjdHBhc3N3b3Jk

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    app: postgres
    type: local
spec:
  #storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: "/var/data/pgsql"
    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    app: sonarqube
spec:
  #storageClassName: manual
  capacity:
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain  
  resources:
    requests:
      storage: 5Gi   