---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-data-pv
  labels:
    app: sonarqube
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: "/opt/sonarqube/data"
    
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-data-pvc
  labels:
    app: sonarqube
spec:
  storageClassName: manual
  capacity:
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain  
  resources:
    requests:
      storage: 5Gi       


---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-extensions-pv
  labels:
    app: sonarqube
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: "/opt/sonarqube/extensions"



---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-extensions-pvc
  labels:
    app: sonarqube
spec:
  storageClassName: manual
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi        
      

#
#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: sonarqube-pv
#spec:
##  selector:
##      jenkins: master
##  storageClassName: jenkins-pv
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: "/opt/sonarqube/"


#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: sonar-extensions-pvc
#spec:
#  accessModes:
#  - ReadWriteOnce
#  storageClassName: default
#  resources:
#    requests:
#      storage: 5Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: sonar-data-pvc
#spec:
#  accessModes:
#  - ReadWriteOnce
#  storageClassName: default
#  resources:
#    requests:
#      storage: 5Gi         